version: '3.3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    restart: always
    ports:
      - 8080:80

  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    env_file:
      - ./packages/backend/.env
    ports:
      - 3333:3333
    networks:
      - nesjs-network
    links:
      - mongodb
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data_container:/data/db
    networks:
      - nesjs-network
    restart: always

volumes:
  data_container: {}

networks:
  nesjs-network:
    driver: bridge